# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'oc-demo-project-pod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oc-demo-project-pod
  pod 'oc-pod', :path => '../oc-pod'
  pod 'swift-pod', :path => '../swift-pod'
end
